const actionTypes = Object.freeze({

    ACCOUNT_LOGIN_START: 'ACCOUNT_LOGIN_START',
    ACCOUNT_LOGIN_SUCCESS: 'ACCOUNT_LOGIN_SUCCESS',
    ACCOUNT_LOGIN_FAIL: 'ACCOUNT_LOGIN_FAIL',
    PROCESS_LOGOUT: 'PROCESS_LOGOUT',
    LOGOUT_SUCCESS: 'LOGOUT_SUCCESS',
    LOGOUT_FAILD: 'LOGOUT_FAILD',
    REGISTER_START: 'REGISTER_START',
    REGISTER_FAILDED: 'REGISTER_FAILDED',
    REGISTER_SUCCESS: 'REGISTER_SUCCESS',
    VERIFY_START: 'VERIFY_START',
    VERIFY_FAILDED: 'VERIFY_FAILDED',
    VERIFY_SUCCESS: 'VERIFY_SUCCESS',
})

export default actionTypes;